### ISSUE TITLE
Problem: metadata.csv does not include all mandatory Datacite fields

### ISSUE THREAD

**Issue by sevein** [JiscRDSS/rdss-archivematica-channel-adapter#28]
Mapping [here](https://jiscdev.atlassian.net/wiki/download/attachments/83496709/SchemaMapping-15-June-Datacite-2-CDM-2-Archivematica.xlsx?version=1&modificationDate=1497556345495&cacheVersion=1&api=v2&download=true)  - this link is not public AFAIK.

To be clear, this is not for the MVP.

**Comment by sevein** [comment]
@peterVG, this is waht you shared with mi in the chatroom. Looks like GH likes it. Feel free to add new comments with a new version if you have to change it, GH should also let you edit your own comments once submitted.

| Datacite 4.0  | JISC-RDSS-CDM v.19-06-2017 |
| ------------- | ------------- |
| datacite:identifier | objectIdentifierValue  |
| datacite:identifierType   | objectIdentifierType |
| datacite:creator |   |
| datacite:creatorName   | ObjectContributor.PersonRole.Person.personGivenName (WHERE ObjectContributor.PersonRole.person = "creator") |
| datacite:title | objectTitle|
| datacite:publisher | ObjectContributor.PersonRole.Person.personGivenName (WHERE ObjectContributor.PersonRole.person = "publisherr") |
| datacite:publicationYear   | ObjectDate.dateValue (where dateType ="published") |
| datacite:resourceType | fileFormatType |
| datacite:resourceTypeGeneral | objectResourceType |

**Comment by peterVG** [comment]
Some more background for clarification on this issue:
For the MVP Alpha release, an objective was set to map the mandatory Datacite 4.0 properties to the latest version of the JISC Canonical Data Model (which specifies the schema to use for RDSS Messaging API message payloads). The rationale was that this minimum baseline of metadata values should be present for all datasets that use a DOI from DataCite, which is expected to be the case for many (majority?) of UK HEI based researchers.
The table above shows the latest version of the mapping that was used to determine which CDM properties to use for this task ( @sevein FYI GH comment preview & online markdown linter only showed me the raw markup for the table so i thought it was bust)
 From the Archivematica development perspective, the decision was made to implement no more than two property mappings at a time to minimize regression errors and to keep the focus on producing a proof-of-concept that demonstrates:
- the flow of metadata external to the preservation system (e.g. from Datacite API, RDSS repository system X, etc), 
- normalized to the RDSS CDM,
- mapped and stored in a rdss-achivematica Archival Information Package (AIP).

The metadata flow proof of concept has been accomplished for MVP Alpha, however, the original objective to import and store all the mandatory DataCite fields, as shown in the mapping above, was not. Please note that this was a sprint/team goal not a project/contractual requirement) 

This is what this issue#28 is referring to: completing the implementation of the mapping in the table above in rdss-archivematica. The rationale is that a RDM preservation product should at least support this core set of Datacite metadata to be 'minimally viable'.

There is no functioning RDSS Message Broker component available at the time of the RDSS-Archivematica MVP alpha release. To test and demonstrate the rdss-archivematica alpha release, we created a simple app to simulate the sending of messages compliant with the latest version of the rdss-messaging-api specification. These are serialized as JSON and given the default name `request.json` to match the spec.

- Alpha MVP [request.json](https://github.com/artefactual-labs/rdss-archivematica-test-data-corpus/blob/master/10.5281/zenodo.46430/metadataFiles/request.json) (all fields are recognized and imported)

- Full mandatory DataCite properties [request.json](https://github.com/artefactual-labs/rdss-archivematica-test-data-corpus/blob/master/10.5281/zenodo.46430/metadataFiles/request_v0.0.4.json).

**Comment by sevein** [comment]
@peterVG do you know if this issue can be closed after the changes in #69?

**Comment by peterVG** [comment]
Yes, while one field (_datacite:resourceType_) is not included I think this issue can be closed because it it is not a straight forward mapping to the CDM and back to DC. Plus this is no longer a release requirement (implement all mandatory DataCite properties). 

These are the DataCite properties and sub-properties with a 'required' Occurence value:

1 | DataCite.ID#1 | datacite:identifier
-- | -- | --
2 | DataCite ID#1.1 | datacite:identifierType
3 | DataCite.ID#2 | datacite:creator
4 | DataCite.ID2.1 | datasite:creatorName
5 | DataCite.ID#3 | datacite:title
6 | DataCite.ID#4 | datacite:publisher
7 | DataCiteID#5 | datacite:publicationYear
8 | DataCite.ID#10 | datacite:resourceType
9 | DataCite.ID#10.1 | datacite:resourceTypeGeneral

This mapping:
https://jiscdev.atlassian.net/wiki/download/attachments/83496709/SchemaMapping-15-June-Datacite-2-CDM-2-Archivematica.xlsx?version=1&modificationDate=1497556345495&cacheVersion=1&api=v2

...is implemented in AM code here: https://github.com/JiscRDSS/rdss-archivematica-channel-adapter/blob/6b4ea6341fe6cdb007449c757facb0bed8371d78/consumer/consumer.go#L192

**Comment by sevein** [comment]
Sweet! Thank you for the detailed response.
